### ISSUE TITLE
Extra args break -v, -vv, -h, --debug-params, --debug-params-json

### ISSUE THREAD

**Issue by leseb** [instructlab/instructlab#1718]
Trying to increase verbosity when running `ilab model serve`:

```
$ ilab model serve -v
INFO 2024-07-15 14:37:19,197 serve.py:120: serve: Using model '/Users/leseb/Library/Application Support/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf' with -1 gpu-layers and 4096 max context size.
INFO 2024-07-15 14:37:19,198 serve.py:124: serve: Serving model '/Users/leseb/Library/Application Support/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf' with llama-cpp
INFO 2024-07-15 14:37:19,198 serving_backend:0: flush: ['-v']
ERROR 2024-07-15 14:37:19,199 serving_backend:0: flush: Traceback (most recent call last):
  File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
ERROR 2024-07-15 14:37:19,199 serving_backend:0: flush: ^^^^^^^^^^^^^^^^
ERROR 2024-07-15 14:37:19,200 serving_backend:0: flush: File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
ERROR 2024-07-15 14:37:19,200 serving_backend:0: flush: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 2024-07-15 14:37:19,200 serving_backend:0: flush: File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
ERROR 2024-07-15 14:37:19,200 serving_backend:0: flush: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 2024-07-15 14:37:19,200 serving_backend:0: flush: File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
ERROR 2024-07-15 14:37:19,200 serving_backend:0: flush: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 2024-07-15 14:37:19,201 serving_backend:0: flush: File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
ERROR 2024-07-15 14:37:19,201 serving_backend:0: flush: ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 2024-07-15 14:37:19,201 serving_backend:0: flush: File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
ERROR 2024-07-15 14:37:19,201 serving_backend:0: flush: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 2024-07-15 14:37:19,201 serving_backend:0: flush: File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.11/site-packages/instructlab/clickext.py", line 196, in wrapper
    return f(*args, **kwargs)
ERROR 2024-07-15 14:37:19,201 serving_backend:0: flush: ^^^^^^^^^^^^^^^^^^
ERROR 2024-07-15 14:37:19,201 serving_backend:0: flush: File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.11/site-packages/instructlab/model/serve.py", line 149, in serve
    ctx.fail(f"Unsupported extra arguments: {', '.join(ctx.args)}")
ERROR 2024-07-15 14:37:19,201 serving_backend:0: flush: File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 684, in fail
    raise UsageError(message, self)
ERROR 2024-07-15 14:37:19,201 serving_backend:0: flush: click.exceptions.UsageError: Unsupported extra arguments: -v
ERROR 2024-07-15 14:37:19,201 serving_backend:0: flush: 
ERROR 2024-07-15 14:37:19,201 serving_backend:0: flush: During handling of the above exception, another exception occurred:
ERROR 2024-07-15 14:37:19,201 serving_backend:0: flush: Traceback (most recent call last):
  File "/Users/leseb/Documents/AI/instructlab/venv/bin/ilab", line 8, in <module>
    sys.exit(ilab())
ERROR 2024-07-15 14:37:19,201 serving_backend:0: flush: ^^^^^^
ERROR 2024-07-15 14:37:19,202 serving_backend:0: flush: File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
ERROR 2024-07-15 14:37:19,202 serving_backend:0: flush: ^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 2024-07-15 14:37:19,202 serving_backend:0: flush: File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1095, in main
    e.show()
ERROR 2024-07-15 14:37:19,202 serving_backend:0: flush: File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.11/site-packages/click/exceptions.py", line 78, in show
    echo(f"{self.ctx.get_usage()}\n{hint}", file=file, color=color)
ERROR 2024-07-15 14:37:19,202 serving_backend:0: flush: File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
ERROR 2024-07-15 14:37:19,203 serving_backend:0: flush: ^^^^^^^^^^^^^^^
ERROR 2024-07-15 14:37:19,203 serving_backend:0: flush: File "/Users/leseb/Documents/AI/instructlab/venv/lib/python3.11/site-packages/click/_compat.py", line 99, in __getattr__
    return getattr(self._stream, name)
ERROR 2024-07-15 14:37:19,203 serving_backend:0: flush: ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 2024-07-15 14:37:19,203 serving_backend:0: flush: AttributeError: 'str' object has no attribute 'write'
```

The code gets confused with the use of extra argument as introduced in https://github.com/instructlab/instructlab/commit/9a0c6f3ffdabe651178b3bc665a5eb8549997de8.

**Comment by leseb** [comment]
What's interesting is that I thought `ctx.args` would represent strings passed after `--`, that does not seem to be the case.

**Comment by tiran** [comment]
I have not considered this case. Is there a way to configure click to only accept extra args after `--`? Click should not accept unknown args before or without `--` separator.

**Comment by leseb** [comment]
It's interesting because click does not seem to work as advertised in this context. I mean everything after `serve` in this case gets treated as an extra args and populates ctx.args where only things after `--` should.

**Comment by tiran** [comment]
https://github.com/instructlab/instructlab/blob/49622efe32233b4da9fcd4978a8cac6a3a0d506f/src/instructlab/model/serve.py#L18-L20

Maybe `"ignore_unknown_options": True` is the wrong setting? Could you try with `False`?

**Comment by leseb** [comment]
> https://github.com/instructlab/instructlab/blob/49622efe32233b4da9fcd4978a8cac6a3a0d506f/src/instructlab/model/serve.py#L18-L20
> 
> Maybe `"ignore_unknown_options": True` is the wrong setting? Could you try with `False`?

According to click [documentation](https://click.palletsprojects.com/en/5.x/advanced/#forwarding-unknown-options) `"ignore_unknown_options": True` is correct.

**Comment by tiran** [comment]
I think the docs are wrong or at least misleading. `"ignore_unknown_options": False` blocks unknown options but still allows for extra arguments. `context_settings={"allow_extra_args": True, "ignore_unknown_options": False},` behaves like this:

```
$ ilab model serve -v -- --foo
Usage: ilab model serve [OPTIONS]
Try 'ilab model serve --help' for help.

Error: No such option: -v
```

The long traceback is caused by a different issue, #1738
